server:
  port: 8050 # 指定Eureka实例的端口
eureka:
  instance:
    prefer-ip-address: true # 是否显示主机IP
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/  # 指定Eureka服务端地址
spring:
  application:
    name: eurekagatewayzuul #指定应用名称
zuul:
  routes:
    order-serviceId: eurekaorder # zuul的唯一标识
    path: /order/**  #需要映射的路径
    servive-id: eurekaorder # Eureka中的serviceId




